apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-bv-traefik
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  # Lower Cost performance tier (no Performance Units billing).
  # Traefik only writes acme.json (~120 KB, ~no IOPS demand) so
  # we don't need Balanced (10) or Higher Performance (20).
  vpusPerGB: "0"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
