# MySQL HeatWave Connection Resources
# These resources allow K8s applications to connect to OCI MySQL HeatWave
#
# Prerequisites:
# 1. Deploy MySQL HeatWave via Terraform: terraform apply (terraform/05-mysql-heatwave)
# 2. Get the MySQL IP: terraform output mysql_host
# 3. Update the MYSQL_HOST value below with the actual IP
# 4. Update the mysql-secret with your actual password

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # Update these with your MySQL HeatWave credentials
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "<<password-here>>"
  # Connection string for applications
  MYSQL_HOST: "<<heatwave-ip-here>>"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "app"
  # Full DSN for applications that need it
  DATABASE_URL: "mysql://admin:<<password-here>>@<<heatwave-ip-here>>:3306/app"

---
# ExternalName service - allows apps to use 'mysql-service' as hostname
# This provides a stable DNS name that resolves to MySQL HeatWave
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ExternalName
  externalName: "<<heatwave-ip-here>>"  # Replace with actual HeatWave IP

---
# ConfigMap with MySQL connection info (non-sensitive)
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_HOST: "<<heatwave-ip-here>>"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "app"
