apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
type: Opaque
stringData:
  REDIS_PASSWORD: "<<redis-password-here>>"
  # Connection URL for applications (points to master for read/write)
  REDIS_URL: "redis://:<<redis-password-here>>@redis-master.redis.svc.cluster.local:6379"
  # Read-only replica URL
  REDIS_REPLICA_URL: "redis://:<<redis-password-here>>@redis-replica.redis.svc.cluster.local:6379"
