# Redis Commander - Web UI for Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis
  labels:
    app: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: ghcr.io/joeferner/redis-commander:latest
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_HOSTS
              value: "master:redis-master.redis.svc.cluster.local:6379:0:$(REDIS_PASSWORD),replica:redis-replica.redis.svc.cluster.local:6379:0:$(REDIS_PASSWORD)"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  namespace: redis
spec:
  type: NodePort
  selector:
    app: redis-commander
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-commander-ingress
  namespace: redis
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: "redis-redis-commander-auth@kubernetescrd"
spec:
  tls:
    - hosts:
        - redis.junaid.guru
  rules:
    - host: redis.junaid.guru
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: redis-commander-service
                port:
                  number: 8081

---
# Basic auth middleware to protect Redis Commander
apiVersion: v1
kind: Secret
metadata:
  name: redis-commander-secret-auth
  namespace: redis
type: kubernetes.io/basic-auth
stringData:
  username: "<<username-here>>"
  password: "<<password-here>>"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redis-commander-auth
  namespace: redis
spec:
  basicAuth:
    secret: redis-commander-secret-auth
