# Service for Redis Master (read/write)
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis
    role: master
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
  selector:
    app: redis
    role: master

---
# Service for Redis Replica (read-only)
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: redis
  labels:
    app: redis
    role: replica
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
  selector:
    app: redis
    role: replica

---
# Service targeting all Redis pods (master + replica)
# Use for reads when you don't care about consistency
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
  selector:
    app: redis
