apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shehryar-user-full-access
  namespace: shehryar
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shehryar-user-view
  namespace: shehryar
subjects:
  - kind: User
    name: shehryar-user
    namespace: shehryar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shehryar-user-full-access
