name: "Copy Secrets to other project (single)"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jpoehnelt/secrets-sync-action@67585549a2f812eef2bcd8f5f7aeefbfbfe76326
        with:
          SECRETS: |
            ^OCI_.*
          REPOSITORIES: ${{ inputs.repository }}
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
          CONCURRENCY: 10
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
          OCI_COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
          OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
          OCI_OKE_CLUSTER_OCID: ${{ secrets.OCI_OKE_CLUSTER_OCID }}
