apiVersion: core.cs.sap.com/v1alpha1
kind: ClusterSecret
metadata:
  name: ocirsecret
spec:
  namespaceSelector:
    matchLabels:
      registry: "oci"
  template:
    type: kubernetes.io/dockerconfigjson
    data:
      ".dockerconfigjson": "BASE64DATA"
# To get base64 data
# kubectl create secret docker-registry ocirsecret --docker-server=phx.ocir.io --docker-username=ansh81vru1zp/jdoe@acme.com --docker-password='k]j64r{1sJSSF-;)K8' --docker-email=jdoe@acme.com
# kubectl get secret ocirsecret -o jsonpath='{.data}'

