apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: local-webapp-v1
  namespace: test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: lhr.ocir.io/lrhvckxzwf3l/shehryar-personal-site:main
          name: webapp
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ocirsecret
